name: 🐛 Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for using this bundle and taking the time to fill out this bug report !
  - type: input
    id: vite-bundle-version
    attributes:
      label: vite-bundle version
      description: composer show pentatrion/vite-bundle | grep versions
      placeholder: x.y.z
    validations:
      required: true
  - type: input
    id: vite-plugin-symfony-version
    attributes:
      label: vite-plugin-symfony version
      description: npm list vite-plugin-symfony
      placeholder: x.y.z
    validations:
      required: true
  - type: input
    id: context
    attributes:
      label: your OS, Symfony version, PHP version, Node version
      placeholder: "OS Linux, symfony 7.3, PHP 8.2, node 20.5"
      description: Depending on the context choose the most appropriate informations
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the problem
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce
      description: |
        ⚠️  This is the most important part of the report ⚠️
        Without a way to easily reproduce your issue, there is little chance we will be able to help you and work on a fix.
        Please, take the time to show us some code and/or config that is needed for others to reproduce the problem easily.
    validations:
      required: true
  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution
      description: |
        Optional: only if you have suggestions on a fix/reason for the bug
        Don't hesitate to create a pull request with your solution, it helps get faster feedback. You should open a pull request on the main symfony-vite-dev monorepo : https://github.com/lhapaipai/symfony-vite-dev.
        This repository is a "subtree split": a read-only subset of that main repository.
